version: 0.1

phases:
  install:
    commands:
      - mkdir target
      - pip install -t target -r requirements.txt
      - mkdir target
      - cp $TARGET_DIRECTORY/* target/
  pre_build:
    commands:
      - echo hoge
  build:
    commands:
      - echo hoge
artifacts:
  type: zip
  files:
    - "target/*"
  discard-paths: no
