version: 0.1

phases:
  install:
    commands:
      - pip install -t . -r requirements.txt
  pre_build:
    commands:
      - echo hoge
  build:
    commands:
      - echo hoge
artifacts:
  type: zip
  files:
    - "**/*"
  discard-paths: no
